<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.se</groupId>
  <artifactId>demorestdb</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>23672221_NguyenHoangSon</name>
  <packaging>war</packaging>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.target>11</maven.compiler.target>
    <maven.compiler.source>11</maven.compiler.source>
    <junit.version>5.9.2</junit.version>
  </properties>

  <dependencies>
      <!-- 1. Jakarta EE 10 Web API (Provided bởi Tomcat 10) -->
      <dependency>
          <groupId>jakarta.platform</groupId>
          <artifactId>jakarta.jakartaee-web-api</artifactId>
          <version>10.0.0</version>
          <scope>provided</scope>
      </dependency>
      <!-- 2. Jersey Container Servlet (Xử lý REST API) -->
      <dependency>
          <groupId>org.glassfish.jersey.containers</groupId>
          <artifactId>jersey-container-servlet</artifactId>
          <version>3.1.10</version>
      </dependency>
      <!-- 3. Hỗ trợ chuyển đổi JSON (JSON-B / Yasson) -->
      <dependency>
          <groupId>org.glassfish.jersey.media</groupId>
          <artifactId>jersey-media-json-binding</artifactId>
          <version>3.1.10</version>
      </dependency>
      <!-- 4. Injection (HK2) – cho Tomcat chỉ là Servlet container không có sẵn CDI vì
      thế cần dependencies cho Tomcat sử dụng CDI -->
      <dependency>
          <groupId>org.glassfish.jersey.inject</groupId>
          <artifactId>jersey-hk2</artifactId>
          <version>3.1.10</version>
      </dependency>
      <!-- 5. Weld: CDI container cho Tomcat -->
      <dependency>
          <groupId>org.jboss.weld.servlet</groupId>
          <artifactId>weld-servlet-shaded</artifactId>
          <version>5.1.2.Final</version>
      </dependency>
      <!-- 6. Cầu nối Jersey <-> CDI -->
      <dependency>
          <groupId>org.glassfish.jersey.ext.cdi</groupId>
          <artifactId>jersey-cdi1x</artifactId>
          <version>3.1.10</version>
      </dependency>
      <dependency>
          <groupId>org.glassfish.jersey.ext.cdi</groupId>
          <artifactId>jersey-cdi1x-servlet</artifactId>
          <version>3.1.10</version>
      </dependency>
      <!-- 7. MariaDB JDBC Driver -->
      <dependency>
          <groupId>org.mariadb.jdbc</groupId>
          <artifactId>mariadb-java-client</artifactId>
          <version>3.3.5</version>
      </dependency>  </dependencies>

  <build>
    <plugins>
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>
      </plugin>    </plugins>
  </build>
</project>